[feat] 게시글 신고 및 신고취소 기능과 신고 누적 횟수 5회 이상 시 게시글이 조회되지 않는 기능 개발
puppypawpaw/Pawpaw_project_BE pull request #101
Opened 2023-11-07 09:08 UTC by Chaseungjun

2023-11-07 12:34 UTC, lkw1211 requested changes
수고하셨습니다.

2023-11-08 18:40 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/controller/report/ReportController.java
> +@Getter
> 컨트롤러에 Getter가 있는 이유가 있을까요

수정완료

2023-11-08 18:40 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/controller/report/ReportController.java
> +    @PostMapping("/add")
> post 자체가 생성을 의미하는데
> 
> url을 추가로 입력안하시는건 어떻게 생각하시나요?

수정완료

2023-11-09 14:10 UTC, lkw1211 approved these changes
수고하셨습니다

2023-11-09 14:10 UTC, merged