게시판의 이미지 업로드 기능과 썸네일 기능을 구현한다.
puppypawpaw/Pawpaw_project_BE pull request #21
Opened 2023-08-13 15:17 UTC by Chaseungjun

1. 이미지 업로드와 썸네일 기능을 구현한다.
2. 게시글과 이미지 관련 예외코드와 핸들러를 추가한다.
3.  이미지 업로드 테스트 코드를 작성한다.

2023-08-13 15:51 UTC, lkw1211 requested changes

2023-08-13 15:51 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
> +    protected Board() {
@NoArgsConstructor(access = AccessLevel.PROTECTED)
이거 그냥 붙이시면 되여

2023-08-13 15:51 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>          this.isRemoved = true;
soft delete 구현하시는거면
https://velog.io/@max9106/JPA-soft-delete
이거 참고하시면 도움될거같습니다.

2023-08-13 15:51 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
> +    @Builder.Default
@Builder.Default
private Set<BoardImg> imgSet = new HashSet<>();

이거랑
그냥
private final Set<BoardImg> imgSet = new HashSet<>();
의 차이점을 혹시 아시는지 궁금합니다.

2023-08-13 15:51 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      public static Board createBoard(BoardDto.BoardRegisterDto registerDto, User user){
dto안에 메서드를 만들어서 board로 변환하는거랑
지금 이방식이랑 장단점이 무엇인지 궁금합니다.

2023-08-13 15:51 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
List가 아니라 Set으로 구성하신 이유가 잇을까요?
양방향 관계를 의도하신건지 궁금합니다.

2023-08-13 15:51 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
> +    @OneToMany(mappedBy = "board", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
List가 아니라 Set으로 구성하신 이유가 잇을까요?
양방향 관계를 의도하신건지 궁금합니다.

2023-08-13 15:51 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
> +    public void addImage(String uuid, String fileName){
메소드 안에서 생성하기보다 밖에서 생성하고 entity를 전달받는게 좋지 않을까요

2023-08-13 15:51 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/repository/BoardRepository.java
> +    Optional<Board> findByIdWithImages(Long id);
@Param 파라미터에 붙이시는게 좋은것같습니다.
빌드 안되는경우도 존재합니다.

2023-08-13 15:51 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/boardImg/controller/BoardImgRestController.java
> +@Log4j2
slf4j로 통일하시는게 어떨가요

2023-08-13 15:51 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/boardImg/controller/BoardImgRestController.java
> +@RestController
swagger 관련 어노테이션도 추가 부탁드립니다.

2023-08-13 15:51 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/boardImg/controller/BoardImgRestController.java
> +public class BoardImgRestController {
cloudflare r2나 aws s3로 파일 관련 이동시킬 예정입니다.
저희 웹사이트가 이미지가 많아 object storage사용하는게 좋을거같습니다.

2023-08-13 15:51 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/exception/common/GlobalExceptionHandler.java
> +    @ExceptionHandler(BoardNotFoundException.class)
BusinessException만 등록하면됩니다.
부모 클래스만 등록하면 됩니다.
혹시 안되시는거면
제가 수정하겠습니다.

2023-08-14 04:28 UTC, Chaseungjun commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
> +    protected Board() {
> @NoArgsConstructor(access = AccessLevel.PROTECTED) 이거 그냥 붙이시면 되여

네 저걸 붙이면 되는데 imgSet과 연관된 에러가 발생했습니다, 그래서 그냥 생성자를 만들어줬더니 작동하길래 저렇게 썼습니다. 저 어노테이션과 생성자를 직접 코드로 써주는 것과 기능은 동일하니 여기서는 어노테이션을 사용안했습니다.

2023-08-14 04:30 UTC, Chaseungjun commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
> +    @Builder.Default
> @Builder.Default private Set imgSet = new HashSet<>();
> 
> 이거랑 그냥 private final Set imgSet = new HashSet<>(); 의 차이점을 혹시 아시는지 궁금합니다.

빌드를 할때 imgSet에 비어있는 HashSet이 기본으로 들어가는 것과 imgSet 에 들어간 HashSet이 외부에서 수정할 수 없는 불변성을 가지는 것의 차이인데 두 코드가 큰 연관성이 있나요?

2023-08-14 04:32 UTC, Chaseungjun commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      public static Board createBoard(BoardDto.BoardRegisterDto registerDto, User user){
> dto안에 메서드를 만들어서 board로 변환하는거랑 지금 이방식이랑 장단점이 무엇인지 궁금합니다.

저는 처음에 공부할 때, 엔티티와 직접적인 관련성이 있는 코드는 엔티티 클래스에 둔다고 공부를 해서 저렇게 썼습니다. 말씀하신 방식으로 해도 문제가 없죠. 잘 모르지만 어느 계층에서 관리를 하느냐의 차이가 있을 것 같습니다. 저는 이 방식이 익숙해서 이렇게 썼습니다.

2023-08-14 04:34 UTC, Chaseungjun commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
> List가 아니라 Set으로 구성하신 이유가 잇을까요? 양방향 관계를 의도하신건지 궁금합니다.

일반적으로 게시글을 지우면 게시글의 이미지와 좋아요가 함께 삭제되는 것을 생각합니다. 그래서 orphanRemoval 을 사용했는데 orphanRemoval 는 리스트에서는 사용할 수가 없습니다. 그래서 Set을 사용했습니다.

2023-08-14 04:36 UTC, Chaseungjun commented on src/main/java/com/puppy/pawpaw_project_be/exception/common/GlobalExceptionHandler.java
> +    @ExceptionHandler(BoardNotFoundException.class)
> BusinessException만 등록하면됩니다. 부모 클래스만 등록하면 됩니다. 혹시 안되시는거면 제가 수정하겠습니다.

그렇네요 BusinessException를 상속받고 있으니 상위클래스로 모두 처리가 가능하네요

2023-08-14 11:53 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
진짜 안되는게 맞나요?

2023-08-14 11:58 UTC, Chaseungjun commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
> 진짜 안되는게 맞나요?

되네요..? 제가 언제부터 이렇게 잘못 알고 있었는지 모르겠네요

2023-08-14 12:16 UTC, lkw1211 requested changes

2023-08-14 12:16 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
board가 지워질 경우 boardLikes 삭제 쿼리는 몇개가 나가나요?
Set 과 List 간의 성능 차이가 있을까요?

2023-08-14 14:18 UTC, Chaseungjun commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
> board가 지워질 경우 boardLikes 삭제 쿼리는 몇개가 나가나요? Set 과 List 간의 성능 차이가 있을까요?

Set은 중복이 없으니 board에 있는 boardLikes 숫자만큼 삭제 쿼리가 나가겠네요.  List는 중복을 허용하니까 제 생각에 중복된 좋아요 숫자만큼 쿼리가 더 나가지 않을까요

2023-08-14 14:34 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
좋아요가 10만개면 삭제 쿼리가 10만개 나가겠네요?
너무 많은거 같지 않나요?

여기서 list가 아닌 set을 써야하는 이유가 잇을까요?(성능 등등)

2023-08-14 14:56 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
두개는 서로 다른 질문입니다.

2023-08-14 15:33 UTC, Chaseungjun commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
> 두개는 서로 다른 질문입니다.

많은 데이터를 수정, 삭제하기 위해 벌크연산이라는 것이 있네요. @Query와 @Modifying을 사용하는데 @Query는 select연산만 지원하기 때문에 수정이나 삭제를 위해서는 @Modifying를 같이 사용해야하고.. DB의 값은 바뀌지만 캐시의 값은 기존의 것이 남아있기 때문에 clearAutomatically = true 옵션으로 비워주는 방식. 강의를 보고 배웠던건데 역시 직접 안써보면 머리에 안남네요. 이번에 찾아보면서 머리에 제대로 들어왔습니다.

여기서 set을 사용하는 이유는 아까 말한 것처럼 중복제거 말고는 생각나는건 없습니다.  List를 사용하면 중복된 값을 허용하게 되니까 회원 한 명이 하나의 게시글에 좋아요를 여러 번 누를 수 있는 상황이 되고요

2023-08-14 15:40 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
현재 상황에서 delete를 벌크로 하기위해서 반드시 @Query가 필요한가요?
clearAutomatically = true를 하지않으면 벌크 삭제 시 항상 디비값과 영속성 컨텍스트 간의 괴리가 발생하나요?

현재 상황이 Set이나 List 둘중 하나를 꼭 사용해야하는 상황인가요?
상관이 없다면 둘중 어떤 것이 더 성능이 좋은가요?

2023-08-15 05:31 UTC, Chaseungjun commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
> 현재 상황에서 delete를 벌크로 하기위해서 반드시 @query가 필요한가요? clearAutomatically = true를 하지않으면 벌크 삭제 시 항상 디비값과 영속성 컨텍스트 간의 괴리가 발생하나요?
> 
> 현재 상황이 Set이나 List 둘중 하나를 꼭 사용해야하는 상황인가요? 상관이 없다면 둘중 어떤 것이 더 성능이 좋은가요?

지금 좋아요 삭제는 deleteBoardLikesByUserAndBoard 이렇게 Spring Data Jpa가 제공하는 기능이 자동으로 쿼리를 만들어 주기 때문에 @Query를 사용해서 쿼리를 따로 작성할 필요는 없을거 같습니다.

영속성 컨텍스트와 DB와의 차이는 저런방식의 데이터 수정이 일어난 후, 동일한 트랙잭션 안에서 값을 읽을 때 1차 캐시를 가져와서 Db와 값의 차이가 발생하는건데, 
만약 벌크연산 트랜잭션 내부에서 값을 읽는게 아니라 벌크연산 트랜잭션이 종료되고.. 다른 트랜잭션에서 값을 읽는다면 영속성 컨택스트가 다시 DB에서 값을 조회하고 그 값을 1차캐시와 비교해서 다르다면 1차캐시의 값을 Db에서 조회한 값으로 업데이트 합니다.  그러면 clearAutomatically = true를 사용하지 않아도 DB와 1차캐시간의 차이가 발생하지 않겠네요.

 Set과 List문제는 찾아보니 전혀 몰랐던걸 발견했습니다. Set을 사용하면 데이터를 입력받을때 중복검사를 하기 위해 Lazy로딩관계에 있더라도 DB에 접근해서 데이터를 조회하는 과정이 발생하는군요. 여기서 Set<BoardLikes> 으로 하면 게시글에 회원이 좋아요를 누를떄 누른적이 있는지 검사를 하기 위해 BoardLike의 모든 데이터를 조회하고요. 그럼 List<BoardLikes>로 바꾸면 좋겠네요. 중복을 검사하는 checkLikeExist메서드를 사용하기 때문에 List에 중복이 들어갈 걱정은 안해도 될 것 같습니다.

2023-08-15 05:49 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
1차캐시와 조회한 엔티티의 어떤 값을 기준으로 비교를 하는건가요?

트랜잭션이 종료되지 않은 시점에도 벌크 연산이 실행 완료되었으면 다른 트랜잭션에서 변경여부를 알 수 있는건가요?
트랜잭션이 벌크 연산 이후에 예외에 의해서 롤백되었을 때 벌크 연산은 그대로 디비에 적용이 되어있나요?

2023-08-15 07:24 UTC, Chaseungjun commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
> 1차캐시와 조회한 엔티티의 어떤 값을 기준으로 비교를 하는건가요?
> @Id로 설정된 엔티티 식별자를 기준으로 비교합니다
> 트랜잭션이 종료되지 않은 시점에도 벌크 연산이 실행 완료되었으면 다른 트랜잭션에서 변경여부를 알 수 있는건가요? 트랜잭션이 벌크 연산 이후에 예외에 의해서 롤백되었을 때 벌크 연산은 그대로 디비에 적용이 되어있나요?
> 트랜잭션이 성공적으로 종료되지 않으면 연산결과는 DB에 반영되지 않고 다른 트랜잭션에서도 변화를 알 수 없습니다.
> 엔티티의 경우 어떤 값이나 메소드를 통해 중복여부를 파악하나요?
> 이 질문을 제가 제대로 이해했는지 모르겠는데, 엔티티 자체의 중복여부 파악은 보통 @Id로 선언되는 PK로 구분하거나 unique로 선언되는 컬럼으로 구분할 수도 있을거같습니다.

2023-08-15 07:27 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
1. 트랜잭션이 종료되지 않은 시점에도 벌크 연산이 실행 완료되었으면 다른 트랜잭션에서 변경여부를 알 수 있는건가요?
2. 트랜잭션이 벌크 연산 이후에 예외에 의해서 롤백되었을 때 벌크 연산은 그대로 디비에 적용이 되어있나요?
3. set은 객체의 중복여부를 어떻게 판단하나요?

2023-08-15 08:17 UTC, Chaseungjun commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
> 1. set은 객체의 중복여부를 어떻게 판단하나요?
> 2. 트랜잭션이 성공적으로 종료되지 않으면 DB에 결과가 반영안된다고 하셨는데,
>    트랜잭션 내부에서 A 엔티티를 저장 후 영속성 컨텍스트를 초기화 하고 A 엔티티를 다시 조회하게 되면
>    조회가 정상적으로 되나요?

equals(), hashcode() 메서드로 객체의 존재여부를 판단한다고하네요. 객체의 주소값과 주소값으로 만든 해시코드로 다른 객체와 비교해서 동일한 객체인지 판단합니다.

조회가 정상적으로 이루어지는 것이 DB를 말하는건가요? 트랜잭션 내부에서 저장, 초기화를 하고 조회를 하면 저장한 값이 영속성 컨텍스트에서는 나오는데 트랜잭션이 성공적으로 종료되지 않았으면 DB에는 안나옵니다

2023-08-15 08:26 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
위에 답변하신대로 구현한다고 하시면 양방향 관계가 필요한가요?

2023-08-15 08:44 UTC, Chaseungjun commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
> 위에 답변하신대로 구현한다고 하시면 양방향 관계가 필요한가요?

게시글과 좋아요만 생각해보면 단방향이 깔끔하긴 합니다. 만약 유저가 자신이 좋아요를 누른 게시글을 모아서 보고 싶다고 한다면, 양방향이 필요할 수도 있고요. 저런 기능 얘기는 없었으니 단방향으로 바꿀까요?

2023-08-15 09:07 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
양방향이 반드시 필요한 경우에만 사용하는것이 좋을 것 같습니다.
특히 필요하더라도 성능에 문제가 발생하는경우면 다른 방법을 생각하는게 나을 것 같습니다.

2023-08-15 13:16 UTC, Chaseungjun commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
> 양방향이 반드시 필요한 경우에만 사용하는것이 좋을 것 같습니다. 특히 필요하더라도 성능에 문제가 발생하는경우면 다른 방법을 생각하는게 나을 것 같습니다. 엔티티 관계만 수정하시면 resolve 하겠습니다. 삭제나 그런것들은 다음 풀리퀘스트 떄 하시면 될 것같습니다.

음 양방향을 단방향으로 바꾸면 게시글과 좋아요의 관계가 1대 다 단방향이 되는데 이때 문제점은 외래키가 반대쪽 테이블에 있다는 점이잖아요. 이 문제를 해결하는 방법이 양방향 맺어버리는건데 그냥 양방향 쓰는 건 어떤가요? 아니면 양방향말고 다른 해결방법 알고 있으신가요?

김영한도 이렇게 실무에서 별 문제 없다고 답글을 쓰기도 했고..
<다대일 양방향 관계로 만들면 이런 불일치 문제를 손쉽게 해결할 수 있습니다. 물론 반대 방향으로 참조 의존관계를 추가해야 하는 것은 단점이지만, 실무에서 크게 영향을 주지는 않습니다.>

2023-08-15 13:54 UTC, lkw1211 commented on src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
>      private Set<BoardLikes> boardLikes = new HashSet<>();
좋아요에 게시글 아이디를 넣으면되죠 그러면 다대일 단방향이죠
영향은 없죠 당연히 근데 안 쓸건데 넣긴좀 그렇죠

2023-08-16 06:18 UTC, closed without merging