댓글, 대댓글 CRUD, 게시글 리스트 조회, BoardLike 관련 클래스 패키지 이동
puppypawpaw/Pawpaw_project_BE pull request #41
Opened 2023-09-06 06:20 UTC by Chaseungjun

1. 댓글과 대댓글 관련 기능 추가
2. 무한스크롤 페이징으로 게시글 조회 기능 추가
3. 댓글과 관련된 예외처리 코드 추가
4. BoardLike 패키지 생성 및 이동

2023-09-06 08:11 UTC, lkw1211 requested changes

2023-09-06 08:11 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +        boardCommand.save(board);
transactional로 dirty checking 되는데
의도하신건가요?

2023-09-06 08:11 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +        boardCommand.save(board);
두번 save를 요청하셨는데 혹시 의도하신걸까요?

2023-09-06 08:11 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +        replyCommand.save(reply);
dirty checking 되는데 의도하신걸까요

2023-09-06 08:11 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +        if (user.getUserId() != reply.getUser().getUserId()) {
reply 조회시 replyId와 유저 id를 같이 넣으면 해당 exception이 없어도 되지 않을까요?

2023-09-06 08:11 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +    public ReplyResponseDto update(@RequestBody ReplyDto.ReplyUpdateDto updateDto, UserId userId, Long replyId) {
@RequestBody 의도하신걸까요?

2023-09-06 08:11 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +            reply.getParent().getChild().forEach(child -> {
getChild에서 n+1발생할거같고
결국엔 reply.updateContent를 하는데
굳이 이렇게 하신 이유가 있을까요?
어차피 db상에서는 child 쪽에만 parent id가 있고
parent에서는 child id가 없는데
위의 검증과정이 필요한가 궁금합니다.

2023-09-06 08:38 UTC, lkw1211 requested changes

2023-09-06 08:38 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +        if (user.getUserId() != parentReply.getUser().getUserId()) {
그냥 userId를 Reply의 쿼리 안에 넣으면 예외가 필요없지 않을까요

2023-09-06 08:38 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +        parentReply.getChild().forEach(child -> {
bulk update 방식을 사용해서
remove상태로 변경하는게 좋을거 같습니다.

2023-09-06 08:38 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +            replyCommand.save(child);
getChild를 한 순간에 영속성 컨텍스트에
영속 상태로 entity가 올라가 dirtyChecking이 진행되지 않나요?

2023-09-06 08:38 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +    private List<ReplyListDto> convertNestedStructure(List<Reply> replyList) {
reply에 ancestor 필드 추가하시고
1. parent가 null이든 ancestor가 null이든 ancestor reply page만큼 조회
2. 1번에서 조회한 ancestor id collection에 속하는 ancestor를 가진 reply list id기준으로 오름차순 조회
3. 1번에서 조회한 ancestor reply를 map에 저장
4. 2번에서 조회한 reply들을 parent로 map에서 조회해서 child에 저장

이 방식은 어떻게 생각하시나요?

2023-09-06 08:38 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/dto/board/BoardDto.java
> +    @Setter
필요하신지는 모르겠으나
왠만하면 setter를 지양하셨으면 좋겠습니다.

2023-09-06 08:38 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/dto/reply/ReplyDto.java
> +    @NoArgsConstructor(access = AccessLevel.PROTECTED)
Entity의 경우에는 프록시 가 entity의 상속 class이기 때문에 PROTECTED이상이 필요하구요
이외에는 reflection 사용하기 때문에 private이어도 생성될겁니다.

2023-09-08 08:47 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +    private List<ReplyListDto> convertNestedStructure(List<Reply> replyList) {
> reply에 ancestor 필드 추가하시고
> 
> 1. ancestor reply(parent가 null이거나 ancestor가 null인) page만큼 조회
> 2. 1번에서 조회한 ancestor reply collection에 속하는 ancestor를 가진 reply들을 id기준으로 오름차순 조회
> 3. 1번에서 조회한 ancestor reply들을 map에 저장(key 는 id, value는 reply entity)
> 4. 2번에서 조회한 reply들을 각각의 parent의 child에 추가 및 map에 저장(key 는 id, value는 reply entity)
> 5. 4번에서 완성된 HashMap의 value 중 ancestor reply들을 list로 변환
> 
> 이 방식은 어떻게 생각하시나요?

설명만 들었을 때는 잘 모르겠어서 프로젝트 완성에 요구되는 기능들을 다 완성한 후에 말씀해주신 방법으로 수정해보겠습니다.

2023-09-08 13:05 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/application/board/BoardService.java
> +    private final BoardRepository boardRepository;
> repository바로 하는거보다 위에 커맨드랑 쿼리로 거쳐서 부탁드립니다.

수정완료

2023-09-08 13:06 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/application/board/BoardService.java
> +                .map(board -> convertBoardToDto(board))
> this::convertBoardToDto로 변경 가능할 거 같습니다.

수정완료

2023-09-08 13:07 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/application/board/BoardService.java
> +        List<ReplyListDto> replyListDtos = board.getReply().stream().map(reply -> {
> 그냥 reply -> new ReplyListDto(reply.getId(), reply.getContent(), reply.getWriter()) 로 해서 return 안보이게 하는게 더 괜찮은거같은데 어떻게 생각하시나요? map 안에 람다식을 따로 분리하는거도 괜찮을거 같구요

수정완료

2023-09-08 13:20 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +    private final ReplyRepository replyRepository;
> repository는 도메인 서비스에서만 접근하는게 좋을거같습니다.

수정완료

2023-09-08 13:20 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +        if (registerDto.getParentId() != null) {
> Reply parentReply = replyQuery.findById(registerDto.getParentId()).orElse(null);
> 
> 이런 방식은 어떻게 생각하시나요

수정완료

2023-09-08 13:21 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +        if (user.getUserId() != reply.getUser().getUserId()) {
> 이게 필요한가요?

수정완료

2023-09-08 13:21 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +        boardCommand.save(board);
> transactional로 dirty checking 되는데 의도하신건가요?

수정완료

2023-09-08 13:21 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +        boardCommand.save(board);
> 두번 save를 요청하셨는데 혹시 의도하신걸까요?

수정완료

2023-09-08 13:21 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +        replyCommand.save(reply);
> dirty checking 되는데 의도하신걸까요

수정완료

2023-09-08 13:21 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +        if (user.getUserId() != reply.getUser().getUserId()) {
> reply 조회시 replyId와 유저 id를 같이 넣으면 해당 exception이 없어도 되지 않을까요?

수정완료

2023-09-08 13:21 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +    public ReplyResponseDto update(@RequestBody ReplyDto.ReplyUpdateDto updateDto, UserId userId, Long replyId) {
> @requestbody 의도하신걸까요?

수정완료

2023-09-08 13:22 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +            reply.getParent().getChild().forEach(child -> {
> getChild에서 n+1발생할거같고 결국엔 reply.updateContent를 하는데 굳이 이렇게 하신 이유가 있을까요? 어차피 db상에서는 child 쪽에만 parent id가 있고 parent에서는 child id가 없는데 위의 검증과정이 필요한가 궁금합니다.

수정완료

2023-09-08 13:22 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +        if (user.getUserId() != parentReply.getUser().getUserId()) {
> 그냥 userId를 Reply의 쿼리 안에 넣으면 예외가 필요없지 않을까요

수정완료

2023-09-08 13:22 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
> +            replyCommand.save(child);
> getChild를 한 순간에 영속성 컨텍스트에 영속 상태로 entity가 올라가 dirtyChecking이 진행되지 않나요?

수정완료

2023-09-08 14:25 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/application/board/BoardService.java
> +        boardListDtos.forEach(boardDto -> {
> convertBoardToDto 에서 replyListDto를 설정해주는거같은데 여기서 추가로 작업을 하는 이유가 있을까요?

수정완료

2023-09-08 14:25 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/dto/board/BoardDto.java
> +    @Setter
> 필요하신지는 모르겠으나 왠만하면 setter를 지양하셨으면 좋겠습니다.

수정완료

2023-09-09 06:37 UTC, lkw1211 approved these changes

2023-09-09 07:27 UTC, simeeeeee approved these changes
확인했습니다. 수고하셨습니다!

2023-09-09 07:46 UTC, merged