[feat] 게시글 이미지 업로드, 조회, 삭제 기능 구현
puppypawpaw/Pawpaw_project_BE pull request #45
Opened 2023-09-12 10:58 UTC by Chaseungjun

1. 게시글 이미지 업로드 기능 구현
2. 이미지 조회 기능 구현
3. 이미지 삭제 기능 구현

2023-09-12 12:43 UTC, lkw1211 requested changes

2023-09-12 12:43 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/application/boardImg/BoardImgService.java
> +                .orElseThrow(() -> new BoardException.BoardNotFoundException());
() -> new BoardException.BoardNotFoundException()이거
BoardException.BoardNotFoundException::new 이렇게 바꿀수 있지 않나요?
이게 더 깔금한거 같습니다.

2023-09-12 12:43 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/application/boardImg/BoardImgService.java
> +        if (uploadDto.getFiles() != null) {
uploadDto가 null인 경우에 exception이 발생하도록
@NotNull validation을 uploadDto에 추가하는게 좋을거같습니다.

컨트롤러 단에서 @Valid를 추가하면 dto에 대한 유효성 검증을 할 겁니다.

그러면 위의 if문 없이도 될거 같습니다.

2023-09-12 12:43 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/application/boardImg/BoardImgService.java
> +            uploadDto.getFiles().forEach(multipartFile -> {
이부분은 그냥 return uploadDto.getFiles().stream().map().collect()
이런식으로 하면 더 깔끔할거 같습니다.
map안의 작업 부분은 따로 함수를 빼서 map(this::<함수명>) 이런식으로 하면
더 깔끔할거 같습니다.

2023-09-12 12:43 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/application/boardImg/BoardImgService.java
> +//                        File thumbFile = new File(uploadPath, "s_" + uuid + "_" + originalFilename);
굳이 필요 없으시면 주석 부분은 지우는게 나을거 같습니다.

2023-09-12 12:43 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/application/boardImg/BoardImgService.java
> +    public ResponseEntity<Resource> viewFileImg(String fileName) {
그냥 Resource리턴하고 controller에서 ResponseEntity.ok()를 하는게 좋지 않을까요

이 경우에는 해당하지 않을 수 있지만

예를 들어 service 레이어 모듈과
controller 레이어 모듈을 분리한다고 했을 때
ResponseEntity에 대한 의존성이
controller 모듈에만 존재하면
Service에서 ResponseEntity에 접근할 때
Service 모듈에도 의존성을 추가 해야 합니다.

2023-09-12 12:43 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/application/boardImg/BoardImgService.java
> +    public Map<String, Boolean> removeUploadFile(String fileName) {
이거는 왜 Map을 반환하는 건가요?

2023-09-12 12:43 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/dto/board/BoardDto.java
> +        public BoardListDto(Long id, String title, String content, String writer, int likedCount, int replyCount, LocalDateTime createdDate, LocalDateTime modifiedDate, List<ReplyListDto> replyListDt
파라미터가 너무 많은 경우에는
여러 라인으로 분리해주시면 가독성이 더 높아질 거 같습니다.

2023-09-15 03:29 UTC, lkw1211 approved these changes

2023-09-15 03:29 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/dto/boardImg/BoardImgDto.java
> +        public String getLink(){
안 쓰는 건 지워주세여

2023-09-16 03:01 UTC, simeeeeee approved these changes
수고하셨습니다!!

2023-09-16 03:01 UTC, merged