[fix] 이미지 업로드 및 조회 코드, 북마크 등록과 조회 코드 수정, nullException 처리
puppypawpaw/Pawpaw_project_BE pull request #93
Opened 2023-10-23 11:22 UTC by Chaseungjun

1. 이미지 업로드 및 조회 코드수정
2. 북마크 등록과 조회 코드 수정
3. nullException 처리
4. 댓글의 등록날짜와 수정날짜 추가

2023-10-23 14:33 UTC, simeeeeee approved these changes
수고하셨습니답!

2023-10-23 21:29 UTC, lkw1211 requested changes

2023-10-23 21:29 UTC, lkw1211 commented on api/src/main/java/kr/co/pawpaw/api/service/board/BoardService.java
> +                        .map(file -> fileService.saveFileByMultipartFile(file, userId))
fileList를 fileUrls로 만드는 것 말고는 따로 사용하지 않아서
fileList대신 fileUrls를 결과로 반환해도 될거같습니다.
file -> fileService.saveFileByMultipartFile(file, userId) 이거를
file -> fileService.saveFileByMultipartFile(file, userId).getFileUrl() 이렇게 바꾸시고
List<File> fileList대신 List<String> fileUrls으로 받으셔도 될 것 같습니다.

2023-10-23 21:30 UTC, lkw1211 commented
리뷰 1개가 끝입니다.

2023-10-24 01:03 UTC, Chaseungjun commented on api/src/main/java/kr/co/pawpaw/api/service/board/BoardService.java
> +                        .map(file -> fileService.saveFileByMultipartFile(file, userId))
> fileList를 fileUrls로 만드는 것 말고는 따로 사용하지 않아서 fileList대신 fileUrls를 결과로 반환해도 될거같습니다. file -> fileService.saveFileByMultipartFile(file, userId) 이거를 file -> fileService.saveFileByMultipartFile(file, userId).getFileUrl() 이렇게 바꾸시고 List fileList대신 List fileUrls으로 받으셔도 될 것 같습니다.

수정완료

2023-10-24 02:55 UTC, lkw1211 approved these changes

2023-10-24 02:55 UTC, merged